### ISSUE TITLE
InvalidOperationException when Navigation.PopModalAsync on UWP

### ISSUE THREAD

**Issue by YZahringer** [daniel-luberda/DLToolkit.Forms.Controls#132]
On UWP, I have an exception when I hide a view who contain a CachedImage:
`InvalidOperationException: Cannot assign a native control without an Element; Renderer unbound and/or disposed. Please consult Xamarin.Forms renderers for reference implementation of OnElementChanged. `
StackTrace: `   at Xamarin.Forms.Platform.UWP.VisualElementRenderer2.SetNativeControl(TNativeElement control)
   at FFImageLoading.Forms.WinUWP.CachedImageRenderer.OnElementChanged(ElementChangedEventArgs1 e)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer2.Dispose(Boolean disposing)
   at FFImageLoading.Forms.WinUWP.CachedImageRenderer.Dispose(Boolean disposing)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer2.Dispose()
   at Xamarin.Forms.Platform.UWP.VisualElementExtensions.Cleanup(VisualElement self)
   at Xamarin.Forms.Platform.UWP.Platform.<SetCurrent>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()`

**Comment by daniel-luberda** [comment]
It's an FFImageLoading issue (other project site), but it should be fixed in 2.2.16-pre. Please submit it on the other site if it's not solved for you.

**Comment by YZahringer** [comment]
Yes it's fixed, thank's
