### ISSUE TITLE
Crash when sequence contains no elements.

### ISSUE THREAD

**Issue by extraPaul** [daniel-luberda/DLToolkit.Forms.Controls#147]
I'm using a FlowListView to display items, and I want my users to be able to filter the items. The FlowListView's item source is an ObservableRangeCollection, which was part of the MasterDetail template when I first created the app and is found in multiple Xamarin Forms example projects.

If the user selects a filter and none of the items match the condition, then no items should appear on the screen. However, when this happens I get a System.InvalidOperationException. Here's the debug trace:

System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <b5bd9d990a0b4733885e90ca5ec6c0fb>:0 
  at DLToolkit.Forms.Controls.FlowObservableCollection`1[T].SyncPrivate (DLToolkit.Forms.Controls.FlowObservableCollection`1[T] currentItems, DLToolkit.Forms.Controls.FlowObservableCollection`1[T] updateItems, System.Boolean notify) [0x00023] in <212d00d727b44fb58cdb773a1c93cbf2>:0 
  at DLToolkit.Forms.Controls.FlowObservableCollection`1[T].Sync (DLToolkit.Forms.Controls.FlowObservableCollection`1[T] newItems, System.Boolean notify) [0x00000] in <212d00d727b44fb58cdb773a1c93cbf2>:0 
  at DLToolkit.Forms.Controls.FlowListView.UpdateContainerList () [0x0001f] in <212d00d727b44fb58cdb773a1c93cbf2>:0 
  at DLToolkit.Forms.Controls.FlowListView.ForceReload (System.Boolean updateOnly) [0x00012] in <212d00d727b44fb58cdb773a1c93cbf2>:0 
  at DLToolkit.Forms.Controls.FlowListView.FlowItemsSourceCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00000] in <212d00d727b44fb58cdb773a1c93cbf2>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_NotifyCollectionChangedEventArgs (object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0000f] in <6c708cf596db438ebfc6b7e012659eee>:0 
  at InvMobilePrototype.Helpers.ObservableRangeCollection`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Specialized.NotifyCollectionChangedAction notificationMode) [0x00082] in Q:\ICAP\Development\Mobile\InvMobilePrototype\InvMobilePrototype\InvMobilePrototype\Helpers\ObservableRangeCollection.cs:54 
  at InvMobilePrototype.Helpers.ObservableRangeCollection`1[T].ReplaceRange (System.Collections.Generic.IEnumerable`1[T] collection) [0x00020] in Q:\ICAP\Development\Mobile\InvMobilePrototype\InvMobilePrototype\InvMobilePrototype\Helpers\ObservableRangeCollection.cs:101 
  at InvMobilePrototype.ViewModels.ProductionCyclePageViewModel.ChangeProductFiltering (System.Int32 filter, System.Int32 hours) [0x0004b] in Q:\ICAP\Development\Mobile\InvMobilePrototype\InvMobilePrototype\InvMobilePrototype\ViewModels\ProductionCyclePageViewModel.cs:174

I'm able to catch the exception, but if I do that the items stay on the screen and it appears as though the filter had no effect. Any suggestions? 

Thanks!

**Comment by ozzy1873** [comment]
More info:
This happens when clearing the observable collection bound to the listview.

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at DLToolkit.Forms.Controls.FlowObservableCollection`1.SyncPrivate(FlowObservableCollection`1 currentItems, FlowObservableCollection`1 updateItems, Boolean notify)
   at DLToolkit.Forms.Controls.FlowListView.UpdateContainerList()
   at DLToolkit.Forms.Controls.FlowListView.ForceReload(Boolean updateOnly)
   at DLToolkit.Forms.Controls.FlowListView.FlowItemsSourceCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
